### ISSUE TITLE
Settings - Fresh install on Ubuntu broken

### ISSUE THREAD

**Issue by laszukdawid** [PRATAP-KUMAR/add-custom-text-to-workspace-indicators#5]
Hi, thanks for your contribution! Was looking forward to checking it out :)

Unfortunately, after fresh install on Ubuntu 24.04.2 / wayland / Gnome 46, and I'm getting the following error when trying to open Settings:

```
The settings of extension AddCustomTextToWorkSpaceIndicators@pratap.fastmail.fm had an error:
\`\`\`
TypeError: (intermediate value).ButtonRow is not a constructor

Stack trace:
  addButton@file:///home/dawid/.local/share/gnome-shell/extensions/AddCustomTextToWorkSpaceIndicators@pratap.fastmail.fm/prefs/pickImage.js:28:34
  fillPreferencesWindow@file:///home/dawid/.local/share/gnome-shell/extensions/AddCustomTextToWorkSpaceIndicators@pratap.fastmail.fm/prefs.js:58:35
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
\`\`\`
```

This was my first extension installed so I might have done something wrong.

**Comment by pratap-panabaka** [comment]
@laszukdawid 

No no, the settings were broken for v46. But it is resolved now.
Please check now and comment back.

Thanks

**Comment by laszukdawid** [comment]
Not sure I understand what you mean? I installed the extension about 10 min ago from https://extensions.gnome.org/extension/6272/add-custom-text-to-workspace-indicators/.

Have you *just now* resolved the issue? Should I uninstall and install from the Gnome Extensions again?

**Comment by pratap-panabaka** [comment]
@laszukdawid 

Yes exactly. I resolved the issue just few seconds before I got your issue. Please uninstall and install it. The version should be 17 from official gnome extensions.

**Comment by laszukdawid** [comment]
Ok, did it just now but the problem persists. Will try again in a few hours in case this is some cashing issue.

**Comment by pratap-panabaka** [comment]
@laszukdawid no no just follow these

```
git clone https://github.com/pratap-panabaka/gse-add-custom-text-to-workspace-indicators
cd gse-add-custom-text-to-workspace-indicators
./uninstall.sh
./install.sh
```

Then refresh gnome-shell or logout and login, then enable the extension.

**Comment by laszukdawid** [comment]
That helped but now I'm being threatened that on a restart the app will be updated by itself. Also, note that the version is 16 (installed from github).

Clicking that "info" button next to the toggle button:
"A new version of this extension is ready and will be loaded on the next login."

<img width="829" height="500" alt="Image" src="https://github.com/user-attachments/assets/2319edd9-e4bc-4332-9a04-d3a5e0d47715" />

**Comment by pratap-panabaka** [comment]
Go ahead
17 is the updated one
